# Generated by Django 6.1 on 2026-08-30 00:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "title",
                    models.CharField(help_text="Title in the default language.", max_length=255),
                ),
                ("theme_code", models.SlugField(blank=True, default="", max_length=64)),
                ("allow_anonymous_participation", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SurveyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "definition",
                    models.JSONField(help_text="Normalised definition; the runner's contract."),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 of the normalised definition.", max_length=64
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", help_text="File it was loaded from.", max_length=512
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="prolog_surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("section_key", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=16)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Presentation index across the whole instrument."
                    ),
                ),
                ("text", models.TextField(help_text="Question text in the default language.")),
                ("required", models.BooleanField(default=True)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["survey_version", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("order", models.PositiveIntegerField()),
                ("label", models.TextField(help_text="Label in the default language.")),
                ("exclusive", models.BooleanField(default=False)),
                ("free_text", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="prolog_surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "key"), name="prolog_option_key_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                fields=("survey", "version"), name="prolog_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("survey",),
                name="prolog_one_active_version_per_survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                fields=("survey_version", "key"), name="prolog_question_key_unique"
            ),
        ),
    ]
