# The whole schema in one migration. PROlog had no release when its tables moved
# into PRomop's chain, so the seven migrations that grew during development were
# collapsed here rather than carried into a host database forever. From the first
# tag on they are append-only.
#
# The participant foreign keys are added conditionally at the end: they point at
# a model the host names (DEP-2), and there is nothing to point at in a
# deployment that names none, so both profiles share one migration state.

# Generated by Django 5.2.17 on 2026-09-02 20:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

PARTICIPANT_MODEL = getattr(settings, "PROLOG_PARTICIPANT_MODEL", None)


def _participant_links():
    """Built lazily: none of these fields can be constructed without a target."""
    if not PARTICIPANT_MODEL:
        return []
    return [
        migrations.AddField(
            model_name="surveyresponse",
            name="participant",
            # Not nullable (DEP-2/RUN-2). Safe as an AddField because the table
            # is created empty in this same migration.
            field=models.ForeignKey(
                help_text="Never null (DEP-2/RUN-2): where nobody is signed in the host mints one.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prolog_survey_responses",
                to=PARTICIPANT_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyinvitation",
            name="participant",
            # Optional: an invitation may be an address and nothing else (RUN-5).
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prolog_survey_invitations",
                to=PARTICIPANT_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mintedparticipant",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prolog_minted",
                to=PARTICIPANT_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantmergecandidate",
            name="minted",
            field=models.ForeignKey(
                help_text="The participant the response is bound to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prolog_merge_candidates",
                to=PARTICIPANT_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantmergecandidate",
            name="existing",
            field=models.ForeignKey(
                help_text="The participant the address already belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prolog_merge_claims",
                to=PARTICIPANT_MODEL,
            ),
        ),
    ]


class Migration(migrations.Migration):
    initial = True

    dependencies = []
    if PARTICIPANT_MODEL:
        dependencies.append(migrations.swappable_dependency(PARTICIPANT_MODEL))

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "title",
                    models.CharField(help_text="Title in the default language.", max_length=255),
                ),
                ("theme_code", models.SlugField(blank=True, default="", max_length=64)),
                ("allow_anonymous_participation", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="MintedParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this participant gained an account (CON-4).",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["identified_at"], name="prolog_surv_identif_b36635_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ParticipantMergeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When a human settled this pair.", null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["resolved_at"], name="prolog_surv_resolve_f861d2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("language", models.CharField(blank=True, default="", max_length=12)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="prolog_surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAdministration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("due_at", models.DateField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="prolog_surveys.surveyinvitation",
                    ),
                ),
            ],
            options={
                "ordering": ["invitation", "due_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("language", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("submitted", "Submitted")],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_question_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "user_agent_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Salted hash; never the raw user agent.",
                        max_length=64,
                    ),
                ),
                (
                    "identity_linked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When identity capture linked this response (CON-4).",
                        null=True,
                    ),
                ),
                (
                    "administration",
                    models.OneToOneField(
                        blank=True,
                        help_text="The invitation occurrence this response answers (RUN-5).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="response",
                        to="prolog_surveys.surveyadministration",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consent_version", models.CharField(max_length=64)),
                (
                    "text_hash",
                    models.CharField(help_text="SHA-256 of the notice shown.", max_length=64),
                ),
                ("language", models.CharField(max_length=12)),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="prolog_surveys.surveyresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "definition",
                    models.JSONField(help_text="Normalised definition; the runner's contract."),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 of the normalised definition.", max_length=64
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", help_text="File it was loaded from.", max_length=512
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="prolog_surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="survey_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="prolog_surveys.surveyversion",
            ),
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("section_key", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=16)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Presentation index across the whole instrument."
                    ),
                ),
                ("text", models.TextField(help_text="Question text in the default language.")),
                ("required", models.BooleanField(default=True)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["survey_version", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("language", models.CharField(blank=True, default="", max_length=12)),
                (
                    "consent_text",
                    models.TextField(help_text="The notice shown when the address was given."),
                ),
                ("captured_on", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_on"],
            },
        ),
        migrations.AddField(
            model_name="surveyadministration",
            name="survey_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Scheduled version; null = the version active when the participant starts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="administrations",
                to="prolog_surveys.surveyversion",
            ),
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("order", models.PositiveIntegerField()),
                ("label", models.TextField(help_text="Label in the default language.")),
                ("exclusive", models.BooleanField(default=False)),
                ("free_text", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="prolog_surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "key"), name="prolog_option_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_key", models.CharField(max_length=128)),
                (
                    "value",
                    models.JSONField(help_text="Canonical value shape for the question type."),
                ),
                (
                    "option_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Selected option keys (single/multi/ranking) for querying.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="prolog_surveys.surveyresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["response", "question_key"],
                "indexes": [
                    models.Index(fields=["question_key"], name="prolog_surv_questio_dca868_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("response", "question_key"), name="prolog_answer_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                fields=("survey", "version"), name="prolog_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("survey",),
                name="prolog_one_active_version_per_survey",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey_version", "status", "started_at"],
                name="prolog_surv_survey__e1f867_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                condition=models.Q(("status", "in_progress")),
                fields=["updated_at"],
                name="prolog_response_inprogress_upd",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                fields=("survey_version", "key"), name="prolog_question_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyadministration",
            constraint=models.UniqueConstraint(
                fields=("invitation", "due_at"), name="prolog_administration_unique"
            ),
        ),
    ] + _participant_links()
