# Generated by Django 6.1 on 2026-08-30 00:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prolog_surveys", "0001_survey_versions"),
    ]

    operations = [
        migrations.CreateModel(
            # Contact rows carry no join key to a response (CON-3): a random pk
            # and a capture *date*, so nothing pairs a contact with the
            # response whose capture marker was written in the same request.
            name="SurveyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("language", models.CharField(blank=True, default="", max_length=12)),
                (
                    "consent_text",
                    models.TextField(help_text="The notice shown when the address was given."),
                ),
                ("captured_on", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_on"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("language", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("submitted", "Submitted")],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_question_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "user_agent_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Salted hash; never the raw user agent.",
                        max_length=64,
                    ),
                ),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consent_version", models.CharField(max_length=64)),
                (
                    "text_hash",
                    models.CharField(help_text="SHA-256 of the notice shown.", max_length=64),
                ),
                ("language", models.CharField(max_length=12)),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="prolog_surveys.surveyresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_key", models.CharField(max_length=128)),
                (
                    "value",
                    models.JSONField(help_text="Canonical value shape for the question type."),
                ),
                (
                    "option_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Selected option keys (single/multi/ranking) for querying.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="prolog_surveys.surveyresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["response", "question_key"],
            },
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey_version", "status", "started_at"],
                name="prolog_surv_survey__e1f867_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyanswer",
            index=models.Index(fields=["question_key"], name="prolog_surv_questio_dca868_idx"),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question_key"), name="prolog_answer_unique"
            ),
        ),
    ]
