# Generated by Django 6.1 on 2026-08-30 00:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prolog_surveys", "0002_responses"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="identity_linked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When identity capture linked this response (CON-4).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SurveyAdministration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("due_at", models.DateField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scheduled version; null = the version active when the participant starts.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrations",
                        to="prolog_surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["invitation", "due_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="administration",
            field=models.OneToOneField(
                blank=True,
                help_text="The invitation occurrence this response answers (RUN-5).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response",
                to="prolog_surveys.surveyadministration",
            ),
        ),
        migrations.CreateModel(
            name="SurveyInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("language", models.CharField(blank=True, default="", max_length=12)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="prolog_surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyadministration",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administrations",
                to="prolog_surveys.surveyinvitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyadministration",
            constraint=models.UniqueConstraint(
                fields=("invitation", "due_at"), name="prolog_administration_unique"
            ),
        ),
    ]
