# Generated by Django 5.2.17 on 2026-09-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prolog_surveys", "0002_publish_a_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycontact",
            name="consents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="surveycontact",
            name="receipt",
            field=models.CharField(blank=True, db_index=True, default="", max_length=43),
        ),
        migrations.CreateModel(
            name="SurveyCaptureConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("text", models.TextField(help_text="The consent wording shown, verbatim.")),
                ("text_hash", models.CharField(max_length=64)),
                ("language", models.CharField(max_length=12)),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_consents",
                        to="prolog_surveys.surveyresponse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("response", "key"), name="one_capture_consent_per_key"
                    )
                ],
            },
        ),
    ]
