# Generated by Django 6.1 on 2026-08-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prolog_surveys", "0003_invitations"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                condition=models.Q(("status", "in_progress")),
                fields=["updated_at"],
                name="prolog_response_inprogress_upd",
            ),
        ),
    ]
